//! Parity tests against PSScriptAnalyzer's `Invoke-Formatter`.
//!
//! Fixtures under `tests/pssa-parity/expected/` were generated by
//! `generate.ps1` with the module version pinned in `expected/VERSION`.
//! Each fixture is `<input>.<profile>.ps1`; the profile maps to a
//! [`FormatOptions`] below. The command catalog (`catalog.json`) was dumped
//! from the same PowerShell session so command/parameter casing is exercised
//! without a runspace.

use pwsh_formatter::{
    BraceStyle, BranchKeywordPlacement, FormatOptions, JsonCatalog, PipelineIndentation,
    format_with_catalog,
};
use std::path::PathBuf;

fn parity_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/pssa-parity")
}

fn no_rules() -> FormatOptions {
    FormatOptions {
        place_open_brace: false,
        place_close_brace: false,
        space_before_open_brace: false,
        space_inside_brace: false,
        space_after_keyword: false,
        space_around_operator: false,
        space_after_separator: false,
        space_around_pipe: false,
        collapse_space_around_pipe: false,
        collapse_space_between_parameters: false,
        indentation: false,
        align_assignment: false,
        keyword_casing: false,
        operator_casing: false,
        command_casing: false,
        ..FormatOptions::default()
    }
}

fn profile_options(profile: &str) -> FormatOptions {
    match profile {
        "default" | "stroustrup" => FormatOptions::default(),
        "otbs" => FormatOptions {
            branch_keyword_placement: BranchKeywordPlacement::Cuddled,
            ..FormatOptions::default()
        },
        "allman" => FormatOptions {
            brace_style: BraceStyle::NextLine,
            ..FormatOptions::default()
        },
        "expand-oneline" => FormatOptions {
            ignore_one_line_block: false,
            ..FormatOptions::default()
        },
        "tabs-noindent" => FormatOptions {
            use_tabs: true,
            pipeline_indentation: PipelineIndentation::NoIndentation,
            ..FormatOptions::default()
        },
        "pipeline-every" => FormatOptions {
            indentation: true,
            pipeline_indentation: PipelineIndentation::IncreaseIndentationAfterEveryPipeline,
            ..no_rules()
        },
        "pipeline-none" => FormatOptions {
            indentation: true,
            pipeline_indentation: PipelineIndentation::None,
            ..no_rules()
        },
        "pipe-redundant" => FormatOptions {
            space_before_open_brace: true,
            space_inside_brace: true,
            space_after_keyword: true,
            space_around_operator: true,
            space_after_separator: true,
            space_around_pipe: true,
            collapse_space_around_pipe: true,
            collapse_space_between_parameters: true,
            ..no_rules()
        },
        other => panic!("unknown profile {other}"),
    }
}

fn catalog() -> JsonCatalog {
    let path = parity_dir().join("catalog.json");
    let json = std::fs::read_to_string(path).expect("catalog.json");
    JsonCatalog::from_json(&json).expect("catalog parses")
}

fn first_difference(a: &str, b: &str) -> String {
    for (i, (la, lb)) in a.lines().zip(b.lines()).enumerate() {
        if la != lb {
            return format!("line {}:\n  expected: {la:?}\n  actual:   {lb:?}", i + 1);
        }
    }
    format!(
        "line counts differ: expected {} vs actual {}",
        a.lines().count(),
        b.lines().count()
    )
}

fn run_case(input_name: &str, profile: &str) {
    let dir = parity_dir();
    let source = std::fs::read_to_string(dir.join("inputs").join(format!("{input_name}.ps1")))
        .expect("input");
    let expected_path = dir
        .join("expected")
        .join(format!("{input_name}.{profile}.ps1"));
    let expected = std::fs::read_to_string(&expected_path)
        .unwrap_or_else(|e| panic!("missing fixture {}: {e}", expected_path.display()));

    let options = profile_options(profile);
    let cat = catalog();
    let result = format_with_catalog(&source, &options, &cat);
    assert!(
        result.formatted,
        "{input_name}.{profile}: formatting skipped"
    );
    assert_eq!(
        result.text,
        expected,
        "\n== {input_name}.{profile} diverges from Invoke-Formatter ==\n{}",
        first_difference(&expected, &result.text)
    );

    // Idempotence against the fixture: formatting the expected output must
    // leave it unchanged.
    let again = format_with_catalog(&expected, &options, &cat);
    assert_eq!(
        again.text,
        expected,
        "\n== {input_name}.{profile}: not idempotent on oracle output ==\n{}",
        first_difference(&expected, &again.text)
    );
}

macro_rules! parity {
    ($($name:ident: $input:literal / $profile:literal),* $(,)?) => {
        $(#[test]
        fn $name() {
            run_case($input, $profile);
        })*
    };
}

parity! {
    braces_default: "braces" / "default",
    braces_otbs: "braces" / "otbs",
    braces_allman: "braces" / "allman",
    braces_stroustrup: "braces" / "stroustrup",
    braces_expand: "braces" / "expand-oneline",
    compact_default: "compact" / "default",
    compact_otbs: "compact" / "otbs",
    compact_allman: "compact" / "allman",
    compact_expand: "compact" / "expand-oneline",
    hashtables_default: "hashtables" / "default",
    hashtables_allman: "hashtables" / "allman",
    hashtables_tabs: "hashtables" / "tabs-noindent",
    whitespace_default: "whitespace" / "default",
    whitespace_redundant: "whitespace" / "pipe-redundant",
    pipelines_default: "pipelines" / "default",
    pipelines_every: "pipelines" / "pipeline-every",
    pipelines_none: "pipelines" / "pipeline-none",
    pipelines_noindent: "pipelines" / "tabs-noindent",
    comments_default: "comments" / "default",
    comments_otbs: "comments" / "otbs",
    comments_allman: "comments" / "allman",
    protected_default: "protected" / "default",
    casing_default: "casing" / "default",
    casing_expand: "casing" / "expand-oneline",
    nested_default: "nested" / "default",
    nested_allman: "nested" / "allman",
    nested_tabs: "nested" / "tabs-noindent",
    tabs_default: "tabs" / "default",
    tabs_otbs: "tabs" / "otbs",
    tabs_expand: "tabs" / "expand-oneline",
}
