//! Differential tests against PowerShell's own tokenizer.
//!
//! Fixtures under `tests/powershell-oracle/fixtures/` were generated by
//! `dump-tokens.ps1` with the pinned `pwsh` recorded in `fixtures/VERSION`.
//! Both token streams are normalized to formatter-relevant categories; the
//! `(category, text)` sequences must match, which pins token boundaries and
//! classifications simultaneously.

use powershell_parser::{OperatorKind, TokenKind, tokenize};
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Fixture {
    file: String,
    errors: u32,
    tokens: Vec<OracleToken>,
}

#[derive(Deserialize)]
struct OracleToken {
    k: String,
    t: String,
}

fn oracle_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/powershell-oracle")
}

/// Normalize a Rust-side token to the oracle categories, or None to skip.
fn normalize(kind: TokenKind) -> Option<&'static str> {
    Some(match kind {
        TokenKind::Whitespace | TokenKind::Newline => return None,
        TokenKind::LineComment | TokenKind::BlockComment => "comment",
        TokenKind::StringLiteral => "string1",
        TokenKind::StringExpandable => "string2",
        TokenKind::HereStringLiteral => "herestring1",
        TokenKind::HereStringExpandable => "herestring2",
        TokenKind::Variable => "variable",
        TokenKind::SplattedVariable => "splat",
        TokenKind::Number => "number",
        TokenKind::Parameter => "parameter",
        TokenKind::Identifier | TokenKind::Generic | TokenKind::RawArgument => "word",
        TokenKind::Keyword(_) => "keyword",
        TokenKind::Label => "label",
        // `--%` lexes as a Generic token in PowerShell.
        TokenKind::Operator(OperatorKind::StopParsing) => "word",
        TokenKind::Operator(_) => "op",
        TokenKind::LCurly => "lcurly",
        TokenKind::RCurly => "rcurly",
        TokenKind::AtCurly => "atcurly",
        TokenKind::LParen => "lparen",
        TokenKind::RParen => "rparen",
        TokenKind::AtParen => "atparen",
        TokenKind::DollarParen => "dollarparen",
        TokenKind::LBracket => "lbracket",
        TokenKind::RBracket => "rbracket",
        TokenKind::Comma => "comma",
        TokenKind::Semicolon => "semi",
        TokenKind::Pipe => "pipe",
        TokenKind::AndAnd => "andand",
        TokenKind::OrOr => "oror",
        TokenKind::Unknown => "unknown",
        _ => "op",
    })
}

fn compare_file(name: &str) {
    let dir = oracle_dir();
    let fixture_path = dir.join("fixtures").join(format!("{name}.json"));
    let input_path = dir.join("inputs").join(format!("{name}.ps1"));
    let fixture: Fixture = serde_json::from_str(
        &std::fs::read_to_string(&fixture_path)
            .unwrap_or_else(|e| panic!("missing fixture {}: {e}", fixture_path.display())),
    )
    .expect("fixture parses");
    let source = std::fs::read_to_string(&input_path).expect("input file");

    let ours: Vec<(String, String)> = tokenize(&source)
        .tokens
        .iter()
        .filter_map(|t| normalize(t.kind).map(|k| (k.to_owned(), t.text(&source).to_owned())))
        .collect();
    let theirs: Vec<(String, String)> = fixture
        .tokens
        .iter()
        .map(|t| (t.k.clone(), t.t.clone()))
        .collect();

    if ours != theirs {
        // Find the first divergence for a readable failure.
        let mut i = 0;
        while i < ours.len() && i < theirs.len() && ours[i] == theirs[i] {
            i += 1;
        }
        let window = |v: &[(String, String)]| -> Vec<String> {
            v.iter()
                .skip(i.saturating_sub(2))
                .take(8)
                .map(|(k, t)| format!("{k}:{t:?}"))
                .collect()
        };
        panic!(
            "token stream diverges from pwsh in {} at index {i} (errors={})\n  pwsh: {:?}\n  ours: {:?}",
            fixture.file,
            fixture.errors,
            window(&theirs),
            window(&ours),
        );
    }
}

macro_rules! oracle_tests {
    ($($test_name:ident => $file:literal),* $(,)?) => {
        $(#[test]
        fn $test_name() {
            compare_file($file);
        })*
    };
}

oracle_tests! {
    strings => "strings",
    numbers => "numbers",
    commands => "commands",
    syntax => "syntax",
    edgecases => "edgecases",
    crlf => "crlf",
    upstream_method_invocation => "upstream-MethodInvocation.Tests",
    upstream_redirection => "upstream-RedirectionOperator.Tests",
    upstream_line_continuance => "upstream-LineContinuance.Tests",
    upstream_pssa_editable_text => "upstream-pssa-EditableText.tests",
    ternary => "ternary",
}
