[package]
name                   = "powershell-parser"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
description            = "Lossless, formatter-oriented PowerShell lexer and structural parser"
repository.workspace   = true
license.workspace      = true

[dependencies]
bitflags.workspace = true

[dev-dependencies]
serde.workspace      = true
serde_json.workspace = true

[lints]
workspace = true
