[package]
name                   = "psfmt"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
repository.workspace   = true
license.workspace      = true
publish                = false

[dependencies]
powershell-formatter = { path = "../../crates/powershell-formatter" }
serde_json           = "1"

[lints]
workspace = true
